import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-card-network-assessment-fee-audit",
  "engine": "recovery",
  "title": "Card Network Assessment Fee Audit",
  "shortTitle": "Card Network Assessment Fee Audit",
  "tagline": "Recalculate card-network assessments and operating fees to recover misapplied volume, cross-border, and service charges.",
  "industry": "Payments Cost Assurance",
  "buyer": "Merchants, acquirers, and payment facilitators",
  "uiPort": 4667,
  "apiPort": 5667,
  "accent": "#15803d",
  "currency": "USD",
  "primaryOutcome": "Card Network Assessment Fee Audit converted into governed, evidence-backed financial outcomes",
  "valueNarrative": "Connect network rulebooks, merchant categories, transaction volumes, domestic and cross-border attributes, assessments, switch fees, token fees, statements, and credits in one accountable workflow. Recalculate card-network assessments and operating fees to recover misapplied volume, cross-border, and service charges.",
  "calculation": {
    "actualKey": "chargedAmount",
    "expectedKey": "supportedAmount",
    "actualLabel": "Charged or Paid Amount",
    "expectedLabel": "Evidence-Supported Amount",
    "varianceLabel": "Potential recovery or avoided cost",
    "direction": "actual-minus-expected",
    "finding": "Card Network Assessment Fee Audit evidence indicates a measurable financial exception.",
    "actions": [
      "Validate the effective agreement, eligibility rules, and accountable parties",
      "Reconcile transaction-level operational and financial evidence",
      "Prepare the correction, recovery, or compliance package",
      "Track counterparty response, approval, cash, and preventive control closure"
    ]
  }
},[
feature("network-fee-library","CNA01","Network fee library","Execute network fee library using network rulebooks, merchant categories, transaction volumes, domestic and cross-border attributes, assessments, switch fees, token fees, statements, and credits.","Produce a governed network fee library decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Network / Merchant Portfolio","text","Network / Merchant Portfolio · Standard Case"],["caseReference","Network fee library Reference","text","CNA01-2026-001"],["chargedAmount","Charged or Paid Amount","currency",837500],["supportedAmount","Evidence-Supported Amount","currency",703500],["domainDriver","Fee Family","select","Assessment",["Assessment","Switching","Tokenization"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Network fee library case","Merchant hierarchy case","Transaction volume ingestion case","Domestic cross-border classification case","Assessment basis calculation case"]}),
feature("merchant-hierarchy","CNA02","Merchant hierarchy","Execute merchant hierarchy using network rulebooks, merchant categories, transaction volumes, domestic and cross-border attributes, assessments, switch fees, token fees, statements, and credits.","Produce a governed merchant hierarchy decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Network / Merchant Portfolio","text","Network / Merchant Portfolio · Standard Case"],["caseReference","Merchant hierarchy Reference","text","CNA02-2026-001"],["chargedAmount","Charged or Paid Amount","currency",837500],["supportedAmount","Evidence-Supported Amount","currency",703500],["domainDriver","Fee Family","select","Assessment",["Assessment","Switching","Tokenization"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Network fee library case","Merchant hierarchy case","Transaction volume ingestion case","Domestic cross-border classification case","Assessment basis calculation case"]}),
feature("transaction-volume-ingestion","CNA03","Transaction volume ingestion","Execute transaction volume ingestion using network rulebooks, merchant categories, transaction volumes, domestic and cross-border attributes, assessments, switch fees, token fees, statements, and credits.","Produce a governed transaction volume ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Network / Merchant Portfolio","text","Network / Merchant Portfolio · Standard Case"],["caseReference","Transaction volume ingestion Reference","text","CNA03-2026-001"],["chargedAmount","Charged or Paid Amount","currency",837500],["supportedAmount","Evidence-Supported Amount","currency",703500],["domainDriver","Fee Family","select","Assessment",["Assessment","Switching","Tokenization"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Network fee library case","Merchant hierarchy case","Transaction volume ingestion case","Domestic cross-border classification case","Assessment basis calculation case"]}),
feature("domestic-cross-border-classification","CNA04","Domestic cross-border classification","Execute domestic cross-border classification using network rulebooks, merchant categories, transaction volumes, domestic and cross-border attributes, assessments, switch fees, token fees, statements, and credits.","Produce a governed domestic cross-border classification decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Network / Merchant Portfolio","text","Network / Merchant Portfolio · Standard Case"],["caseReference","Domestic cross-border classification Reference","text","CNA04-2026-001"],["chargedAmount","Charged or Paid Amount","currency",837500],["supportedAmount","Evidence-Supported Amount","currency",703500],["domainDriver","Fee Family","select","Assessment",["Assessment","Switching","Tokenization"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Network fee library case","Merchant hierarchy case","Transaction volume ingestion case","Domestic cross-border classification case","Assessment basis calculation case"]}),
feature("assessment-basis-calculation","CNA05","Assessment basis calculation","Execute assessment basis calculation using network rulebooks, merchant categories, transaction volumes, domestic and cross-border attributes, assessments, switch fees, token fees, statements, and credits.","Produce a governed assessment basis calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Network / Merchant Portfolio","text","Network / Merchant Portfolio · Standard Case"],["caseReference","Assessment basis calculation Reference","text","CNA05-2026-001"],["chargedAmount","Charged or Paid Amount","currency",837500],["supportedAmount","Evidence-Supported Amount","currency",703500],["domainDriver","Fee Family","select","Assessment",["Assessment","Switching","Tokenization"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Network fee library case","Merchant hierarchy case","Transaction volume ingestion case","Domestic cross-border classification case","Assessment basis calculation case"]}),
feature("switch-fee-validation","CNA06","Switch fee validation","Execute switch fee validation using network rulebooks, merchant categories, transaction volumes, domestic and cross-border attributes, assessments, switch fees, token fees, statements, and credits.","Produce a governed switch fee validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Network / Merchant Portfolio","text","Network / Merchant Portfolio · Standard Case"],["caseReference","Switch fee validation Reference","text","CNA06-2026-001"],["chargedAmount","Charged or Paid Amount","currency",837500],["supportedAmount","Evidence-Supported Amount","currency",703500],["domainDriver","Fee Family","select","Assessment",["Assessment","Switching","Tokenization"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Network fee library case","Merchant hierarchy case","Transaction volume ingestion case","Domestic cross-border classification case","Assessment basis calculation case"]}),
feature("token-service-fee-audit","CNA07","Token service fee audit","Execute token service fee audit using network rulebooks, merchant categories, transaction volumes, domestic and cross-border attributes, assessments, switch fees, token fees, statements, and credits.","Produce a governed token service fee audit decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Network / Merchant Portfolio","text","Network / Merchant Portfolio · Standard Case"],["caseReference","Token service fee audit Reference","text","CNA07-2026-001"],["chargedAmount","Charged or Paid Amount","currency",837500],["supportedAmount","Evidence-Supported Amount","currency",703500],["domainDriver","Fee Family","select","Assessment",["Assessment","Switching","Tokenization"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Network fee library case","Merchant hierarchy case","Transaction volume ingestion case","Domestic cross-border classification case","Assessment basis calculation case"]}),
feature("account-updater-fee-audit","CNA08","Account updater fee audit","Execute account updater fee audit using network rulebooks, merchant categories, transaction volumes, domestic and cross-border attributes, assessments, switch fees, token fees, statements, and credits.","Produce a governed account updater fee audit decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Network / Merchant Portfolio","text","Network / Merchant Portfolio · Standard Case"],["caseReference","Account updater fee audit Reference","text","CNA08-2026-001"],["chargedAmount","Charged or Paid Amount","currency",837500],["supportedAmount","Evidence-Supported Amount","currency",703500],["domainDriver","Fee Family","select","Assessment",["Assessment","Switching","Tokenization"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Network fee library case","Merchant hierarchy case","Transaction volume ingestion case","Domestic cross-border classification case","Assessment basis calculation case"]}),
feature("authorization-fee-control","CNA09","Authorization fee control","Execute authorization fee control using network rulebooks, merchant categories, transaction volumes, domestic and cross-border attributes, assessments, switch fees, token fees, statements, and credits.","Produce a governed authorization fee control decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Network / Merchant Portfolio","text","Network / Merchant Portfolio · Standard Case"],["caseReference","Authorization fee control Reference","text","CNA09-2026-001"],["chargedAmount","Charged or Paid Amount","currency",837500],["supportedAmount","Evidence-Supported Amount","currency",703500],["domainDriver","Fee Family","select","Assessment",["Assessment","Switching","Tokenization"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Network fee library case","Merchant hierarchy case","Transaction volume ingestion case","Domestic cross-border classification case","Assessment basis calculation case"]}),
feature("chargeback-fee-validation","CNA10","Chargeback fee validation","Execute chargeback fee validation using network rulebooks, merchant categories, transaction volumes, domestic and cross-border attributes, assessments, switch fees, token fees, statements, and credits.","Produce a governed chargeback fee validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Network / Merchant Portfolio","text","Network / Merchant Portfolio · Standard Case"],["caseReference","Chargeback fee validation Reference","text","CNA10-2026-001"],["chargedAmount","Charged or Paid Amount","currency",837500],["supportedAmount","Evidence-Supported Amount","currency",703500],["domainDriver","Fee Family","select","Assessment",["Assessment","Switching","Tokenization"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Network fee library case","Merchant hierarchy case","Transaction volume ingestion case","Domestic cross-border classification case","Assessment basis calculation case"]}),
feature("volume-tier-calculation","CNA11","Volume tier calculation","Execute volume tier calculation using network rulebooks, merchant categories, transaction volumes, domestic and cross-border attributes, assessments, switch fees, token fees, statements, and credits.","Produce a governed volume tier calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Network / Merchant Portfolio","text","Network / Merchant Portfolio · Standard Case"],["caseReference","Volume tier calculation Reference","text","CNA11-2026-001"],["chargedAmount","Charged or Paid Amount","currency",837500],["supportedAmount","Evidence-Supported Amount","currency",703500],["domainDriver","Fee Family","select","Assessment",["Assessment","Switching","Tokenization"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Network fee library case","Merchant hierarchy case","Transaction volume ingestion case","Domestic cross-border classification case","Assessment basis calculation case"]}),
feature("processor-statement-matching","CNA12","Processor statement matching","Execute processor statement matching using network rulebooks, merchant categories, transaction volumes, domestic and cross-border attributes, assessments, switch fees, token fees, statements, and credits.","Produce a governed processor statement matching decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Network / Merchant Portfolio","text","Network / Merchant Portfolio · Standard Case"],["caseReference","Processor statement matching Reference","text","CNA12-2026-001"],["chargedAmount","Charged or Paid Amount","currency",837500],["supportedAmount","Evidence-Supported Amount","currency",703500],["domainDriver","Fee Family","select","Assessment",["Assessment","Switching","Tokenization"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Network fee library case","Merchant hierarchy case","Transaction volume ingestion case","Domestic cross-border classification case","Assessment basis calculation case"]}),
feature("credit-request-workflow","CNA13","Credit request workflow","Execute credit request workflow using network rulebooks, merchant categories, transaction volumes, domestic and cross-border attributes, assessments, switch fees, token fees, statements, and credits.","Produce a governed credit request workflow decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Network / Merchant Portfolio","text","Network / Merchant Portfolio · Standard Case"],["caseReference","Credit request workflow Reference","text","CNA13-2026-001"],["chargedAmount","Charged or Paid Amount","currency",837500],["supportedAmount","Evidence-Supported Amount","currency",703500],["domainDriver","Fee Family","select","Assessment",["Assessment","Switching","Tokenization"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Network fee library case","Merchant hierarchy case","Transaction volume ingestion case","Domestic cross-border classification case","Assessment basis calculation case"]}),
feature("cash-reconciliation","CNA14","Cash reconciliation","Execute cash reconciliation using network rulebooks, merchant categories, transaction volumes, domestic and cross-border attributes, assessments, switch fees, token fees, statements, and credits.","Produce a governed cash reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Network / Merchant Portfolio","text","Network / Merchant Portfolio · Standard Case"],["caseReference","Cash reconciliation Reference","text","CNA14-2026-001"],["chargedAmount","Charged or Paid Amount","currency",837500],["supportedAmount","Evidence-Supported Amount","currency",703500],["domainDriver","Fee Family","select","Assessment",["Assessment","Switching","Tokenization"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Network fee library case","Merchant hierarchy case","Transaction volume ingestion case","Domestic cross-border classification case","Assessment basis calculation case"]}),
feature("network-merchant-analytics","CNA15","Network merchant analytics","Execute network merchant analytics using network rulebooks, merchant categories, transaction volumes, domestic and cross-border attributes, assessments, switch fees, token fees, statements, and credits.","Produce a governed network merchant analytics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Network / Merchant Portfolio","text","Network / Merchant Portfolio · Standard Case"],["caseReference","Network merchant analytics Reference","text","CNA15-2026-001"],["chargedAmount","Charged or Paid Amount","currency",837500],["supportedAmount","Evidence-Supported Amount","currency",703500],["domainDriver","Fee Family","select","Assessment",["Assessment","Switching","Tokenization"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Network fee library case","Merchant hierarchy case","Transaction volume ingestion case","Domestic cross-border classification case","Assessment basis calculation case"]})
]);
